/**
 * File templates for the on-demand Nuxt preview host. The host is a minimal
 * Nuxt 4 SPA that registers the `@revenexx/studio-shared` and
 * `@revenexx/studio-integrations` Nuxt modules (the latter ships its own pages
 * under `/integrations`), pointed at the devkit's mock API. No custom auth shim is
 * needed — studio-shared's standalone `usePlatformAuth`/`usePlatformTenant`
 * read a dev token/tenant from `NUXT_PUBLIC_DEV_TOKEN` / `NUXT_PUBLIC_DEV_TENANT`.
 */

/** Peer versions mirrored from `@revenexx/studio-integrations`'s peerDependencies. */
const VERSIONS = {
  nuxt: '^4.0.0',
  vue: '^3.5.0',
  studio: '^0.1.3',
  studioShared: '^0.2.0',
  studioIntegrations: '^0.5.1',
  vueFlowCore: '^1.48.2',
  vueFlowBackground: '^1.3.2',
  vueFlowControls: '^1.1.3',
  vueFlowMinimap: '^1.5.4',
  vueFlowNodeToolbar: '^1.1.1',
  dagre: '^3.0.0',
  lucide: '^1.0.0',
  solarIcons: '^1.2.1',
  // studio-integrations 0.5.x embeds a TipTap rich-text editor and vue-sonner toasts.
  tiptap: '^3.28.0',
  vueSonner: '^2.0.0',
  tailwindVite: '^4.0.0',
  tailwind: '^4.0.0',
};

export interface PreviewTemplateOptions {
  /** Default mock API base URL baked into `.env` (runtime env still overrides). */
  integrationsApiUrl: string;
}

const PACKAGE_JSON = `{
  "name": "integrations-preview-host",
  "private": true,
  "type": "module",
  "scripts": {
    "dev": "nuxt dev",
    "build": "nuxt build"
  },
  "dependencies": {
    "@revenexx/studio": "${VERSIONS.studio}",
    "@revenexx/studio-integrations": "${VERSIONS.studioIntegrations}",
    "@revenexx/studio-shared": "${VERSIONS.studioShared}",
    "@solar-icons/nuxt": "${VERSIONS.solarIcons}",
    "@dagrejs/dagre": "${VERSIONS.dagre}",
    "@tiptap/core": "${VERSIONS.tiptap}",
    "@tiptap/extension-document": "${VERSIONS.tiptap}",
    "@tiptap/extension-history": "${VERSIONS.tiptap}",
    "@tiptap/extension-paragraph": "${VERSIONS.tiptap}",
    "@tiptap/extension-text": "${VERSIONS.tiptap}",
    "@tiptap/pm": "${VERSIONS.tiptap}",
    "@tiptap/vue-3": "${VERSIONS.tiptap}",
    "@vue-flow/background": "${VERSIONS.vueFlowBackground}",
    "@vue-flow/controls": "${VERSIONS.vueFlowControls}",
    "@vue-flow/core": "${VERSIONS.vueFlowCore}",
    "@vue-flow/minimap": "${VERSIONS.vueFlowMinimap}",
    "@vue-flow/node-toolbar": "${VERSIONS.vueFlowNodeToolbar}",
    "lucide-vue-next": "${VERSIONS.lucide}",
    "nuxt": "${VERSIONS.nuxt}",
    "vue": "${VERSIONS.vue}",
    "vue-sonner": "${VERSIONS.vueSonner}"
  },
  "devDependencies": {
    "@tailwindcss/vite": "${VERSIONS.tailwindVite}",
    "tailwindcss": "${VERSIONS.tailwind}"
  }
}
`;

const NUXT_CONFIG = `import tailwindcss from '@tailwindcss/vite';

// Minimal preview host for local integration-node development.
// Generated by \`integrations-devkit init-preview\` — safe to edit or delete
// (it lives under the gitignored .revenexx-dev/).
export default defineNuxtConfig({
  compatibilityDate: '2025-01-01',
  // SPA: no SSR, so the studio's browser-only composables (localStorage etc.)
  // behave exactly as in the real cockpit, and boot is fast.
  ssr: false,
  // studio-shared 0.2.x ships as a Nuxt MODULE (not a layer) — it must be
  // registered in 'modules', before studio-integrations which builds on it.
  // @solar-icons/nuxt provides the #solar-icons alias the studio components import.
  modules: ['@revenexx/studio-shared', '@solar-icons/nuxt', '@revenexx/studio-integrations'],
  css: ['~/assets/css/main.css'],
  vite: { plugins: [tailwindcss()] },
  runtimeConfig: {
    public: {
      // Overridden at runtime by NUXT_PUBLIC_* env (see .env / the preview command).
      integrationsApi: '',
      devToken: '',
      devTenant: '',
    },
  },
});
`;

// Tailwind v4 wiring per @revenexx/studio's README. @source globs are relative
// to THIS file; they tell Tailwind's JIT to scan the shipped component classes
// of studio + studio-shared + studio-integrations, or they render unstyled.
const MAIN_CSS = `@import "tailwindcss";
@import "@revenexx/studio/tokens";
@import "@revenexx/studio/fonts";

@source "../../node_modules/@revenexx/studio/dist";
@source "../../node_modules/@revenexx/studio-shared/components";
@source "../../node_modules/@revenexx/studio-integrations/dist/runtime";

/* Phase 1: workflow EXECUTION is not wired up in the devkit preview yet, so the
   Workflows surface is hidden until phase 2. This hides the sidebar nav entry
   and any deep links to the workflow editor; the routes are also redirected by
   middleware/hide-workflows.global.ts. */
a[href^="/integrations/workflows"] { display: none !important; }
li:has(> a[href^="/integrations/workflows"]) { display: none !important; }
`;

// Shell mirrors services/integrations/studio-ui's app.vue: the studio pages size
// themselves against a definite height (h-svh), the brand background is #f3f1fa,
// and the module's pages call toast.* (vue-sonner) so a global <Toaster> mount is
// required. NuxtLoadingIndicator covers the on-demand route compile in dev.
const APP_VUE = `<script setup lang="ts">
import { Toaster } from '@revenexx/studio'

useHead({ title: 'Integration Studio — devkit preview' })
</script>

<template>
  <div class="flex h-svh flex-col overflow-hidden bg-[#f3f1fa] text-foreground">
    <NuxtLoadingIndicator color="var(--color-primary, #620DFF)" :height="3" />
    <div class="min-h-0 flex-1 pt-3">
      <NuxtPage />
    </div>
    <Toaster rich-colors position="bottom-right" :duration="3500" close-button />
  </div>
</template>
`;

// Landing page styled after services/integrations/studio-ui's pages/index.vue —
// same studio design tokens (bg-card, text-mono, bg-primary, muted) so `/` looks
// like the real dev host. No token gate: the devkit bakes a fixed dev token.
const INDEX_VUE = `<template>
  <div class="mx-auto flex min-h-full max-w-xl flex-col justify-center gap-6 px-6 py-12">
    <div>
      <p class="text-mono text-muted-foreground">Integrations · node devkit</p>
      <h1 class="mt-1 text-2xl font-medium">Integration Studio — Preview</h1>
      <p class="mt-2 text-sm text-muted-foreground">
        Lokaler Host für <code>@revenexx/studio-integrations</code> gegen die Mock-API
        deines Node-Pakets. Authentifizierung ist ein festes Dev-Token — nichts einzugeben.
      </p>
    </div>

    <div class="rounded-lg border border-black/[0.06] bg-card p-5 text-sm shadow-sm">
      <p class="text-mono text-muted-foreground">Session</p>
      <dl class="mt-2 grid grid-cols-[7rem_1fr] gap-y-1">
        <dt class="text-muted-foreground">Mock API</dt>
        <dd class="truncate font-mono text-xs leading-5">{{ api }}</dd>
        <dt class="text-muted-foreground">Tenant</dt>
        <dd class="font-mono text-xs leading-5">{{ tenant }}</dd>
      </dl>
    </div>

    <div class="rounded-lg border border-black/[0.06] bg-card p-5 shadow-sm">
      <p class="text-mono text-muted-foreground">Einstieg</p>
      <div class="mt-3 flex flex-col gap-4">
        <NuxtLink
          to="/nodes"
          class="inline-flex w-fit items-center gap-2 rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground hover:opacity-90"
        >
          Lokale Nodes öffnen — Preview + Validierung
        </NuxtLink>
        <div class="flex flex-wrap gap-x-4 gap-y-1.5">
          <NuxtLink
            v-for="link in quickLinks"
            :key="link.to"
            :to="link.to"
            class="text-sm text-primary hover:underline"
          >
            {{ link.label }}
          </NuxtLink>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
const rc = useRuntimeConfig().public
const api = rc.integrationsApi
const tenant = (rc.devTenant as string) || 'dev-tenant'

const quickLinks = [
  { to: '/integrations', label: 'Overview' },
  { to: '/integrations/credentials', label: 'Credentials' },
  { to: '/integrations/secrets', label: 'Secrets' },
  { to: '/nodes', label: 'Local nodes' },
]
</script>
`;

// Custom devkit page: lists the package's local nodes and, on click, opens the
// REAL editor edit-view by REUSE — the exact studio <Dialog> lightbox from
// WorkflowEditor.vue wrapping <IntegrationsNodeInspector> (the inspector is only
// the dialog CONTENT; the studio Dialog owns the modal chrome/overlay). Config
// fields + dynamic resolving run against the mock. On Save the dialog is kept
// OPEN and the verdict shown: a success strip, or per-field errors fed back
// through the inspector's `refusedFields` prop (wrong fields highlighted). The
// page lives inside a template literal, so no backtick / ${ literals inside —
// API paths use string concatenation.
const NODES_VUE = `<template>
  <div class="ndx-page">
    <div class="ndx-inner">
    <header class="ndx-head">
      <h1>Lokale Nodes</h1>
      <p>Mock-API: <code>{{ apiUrl }}</code></p>
      <p v-if="loadError" class="ndx-err">{{ loadError }}</p>
    </header>

    <p v-if="loading">Lade Nodes…</p>
    <p v-else-if="nodes.length === 0">Keine Nodes gefunden. Exportiert dein Paket <code>NODES</code>?</p>

    <ul v-else class="ndx-grid">
      <li v-for="n in nodes" :key="n.slug + '@' + n.version" class="ndx-card" @click="openNode(n)">
        <div class="ndx-card-title">{{ label(n) }}</div>
        <div class="ndx-card-slug">{{ n.slug }} · v{{ n.version }}</div>
        <div class="ndx-badges">
          <span v-if="n.has_dynamic_options" class="ndx-badge">dynamic options</span>
          <span v-if="n.has_dynamic_schema" class="ndx-badge">dynamic schema</span>
          <span v-if="n.has_dynamic_outputs" class="ndx-badge">dynamic outputs</span>
        </div>
      </li>
    </ul>
    </div>

    <!-- REUSE of the exact editor lightbox: studio <Dialog> owns the modal
         chrome, <IntegrationsNodeInspector> is the content — mirrors
         WorkflowEditor.vue's <Dialog><DialogContent><NodeInspector/> block. -->
    <Dialog :open="!!selection" @update:open="(v) => { if (!v) requestClose() }">
      <DialogContent :show-close-button="false" class="flex h-[min(680px,86vh)] w-[min(1100px,94vw)] max-w-none flex-col gap-0 overflow-hidden rounded-lg p-0 sm:max-w-none">
        <div v-if="result === 'ok'" class="ndx-strip ndx-strip-ok">✓ Payload gültig — alles gut.</div>
        <div v-else-if="result === 'err'" class="ndx-strip ndx-strip-err">✗ Payload ungültig — {{ errorCount }} Feld(er) prüfen (rot markiert).</div>
        <div v-else-if="formError" class="ndx-strip ndx-strip-err">{{ formError }}</div>
        <IntegrationsNodeInspector
          v-if="selection"
          :selection="selection"
          :secret-keys="secretKeys"
          :refused-fields="refused"
          @update="onSubmit"
          @close="requestClose" />
      </DialogContent>
    </Dialog>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { Dialog, DialogContent } from '@revenexx/studio'

interface ApiNode {
  name: string | Record<string, string>
  slug: string
  version: string
  manifest?: { name?: string | Record<string, string> }
  has_dynamic_options?: boolean
  has_dynamic_schema?: boolean
  has_dynamic_outputs?: boolean
}

const apiUrl = useRuntimeConfig().public.integrationsApi
const client = useIntegrationsApi()
// load() fills the reactive catalog the inspector reads via findManifest();
// resolveLocalized() turns a LocalizedString into the active-locale string.
const { load, resolveLocalized } = useIntegrationsNodes()

const nodes = ref<ApiNode[]>([])
const loading = ref(true)
const loadError = ref<string | null>(null)

const selection = ref<any>(null)
const secretKeys = ref<string[]>([])
const refused = ref<Record<string, string>>({})
const result = ref<string | null>(null)
const formError = ref<string | null>(null)
// Set synchronously in onSubmit so the inspector's own Save (it emits update THEN
// close) does NOT close the dialog — we keep it open to show the verdict.
const validating = ref(false)

const errorCount = computed(() => Object.keys(refused.value).length)

function label(n: ApiNode): string {
  return resolveLocalized(n.manifest?.name ?? n.name) || n.slug
}

onMounted(async () => {
  await load()
  try {
    const res = await client.get<any>('/nodes')
    nodes.value = (Array.isArray(res) ? res : res?.data ?? []) as ApiNode[]
  } catch (e: any) {
    loadError.value = e?.message ?? 'Nodes konnten nicht geladen werden.'
  } finally {
    loading.value = false
  }
  try {
    const secrets = await client.get<any>('/secrets')
    const list = (Array.isArray(secrets) ? secrets : secrets?.data ?? []) as Array<{ key: string }>
    secretKeys.value = list.map(s => s.key).filter(Boolean)
  } catch {
    // secrets are optional for the preview
  }
})

function openNode(n: ApiNode) {
  refused.value = {}
  result.value = null
  formError.value = null
  // Synthetic WorkflowNode selection (distinguished by nodeSlug); the inspector
  // resolves its manifest from the catalog load() populated above.
  selection.value = { id: 'preview', nodeSlug: n.slug, nodeVersion: n.version, name: label(n), config: {} }
}

async function onSubmit(draft: any) {
  validating.value = true
  refused.value = {}
  result.value = null
  formError.value = null
  try {
    const slug = encodeURIComponent(draft.nodeSlug)
    const version = encodeURIComponent(draft.nodeVersion || 'latest')
    const res = await client.post<any>(
      '/nodes/' + slug + '/' + version + '/config:validate',
      { config: draft.config ?? {} },
    )
    if (res.valid) {
      result.value = 'ok'
    } else {
      refused.value = Object.fromEntries(
        Object.entries(res.errors ?? {}).map(([k, msgs]) => [k, (msgs as string[]).join(' ')]),
      )
      result.value = 'err'
    }
  } catch (e: any) {
    formError.value = e?.message ?? 'Validierung fehlgeschlagen.'
  } finally {
    validating.value = false
  }
}

// The inspector emits close on both Save and Cancel; the studio Dialog emits it
// on Esc / backdrop. Hold the close while a Save-validation is in flight so the
// dialog stays open to show the result; otherwise close (discard).
function requestClose() {
  if (validating.value) return
  selection.value = null
  refused.value = {}
  result.value = null
  formError.value = null
}
</script>

<style scoped>
/* The app shell (app.vue) is h-svh + overflow-hidden, so this page must own its
   own vertical scroll — otherwise the node list is clipped and can't scroll. */
.ndx-page { height: 100%; overflow-y: auto; }
.ndx-inner { max-width: 60rem; margin: 0 auto; padding: 2rem; font-family: sans-serif; }
.ndx-head h1 { font-size: 1.5rem; font-weight: 600; }
.ndx-err { color: #b91c1c; }
.ndx-grid { list-style: none; padding: 0; display: grid; grid-template-columns: repeat(auto-fill, minmax(15rem, 1fr)); gap: 1rem; margin-top: 1.5rem; }
.ndx-card { border: 1px solid #d1d5db; border-radius: 0.5rem; padding: 1rem; cursor: pointer; transition: border-color .15s, box-shadow .15s; }
.ndx-card:hover { border-color: #6366f1; box-shadow: 0 1px 6px rgba(0,0,0,.08); }
.ndx-card-title { font-weight: 600; }
.ndx-card-slug { color: #6b7280; font-size: .85rem; margin-top: .25rem; }
.ndx-badges { margin-top: .5rem; display: flex; flex-wrap: wrap; gap: .35rem; }
.ndx-badge { font-size: .7rem; background: #eef2ff; color: #4338ca; border-radius: .25rem; padding: .1rem .4rem; }

/* Verdict strip shown at the top of the reused dialog content (does not close). */
.ndx-strip { flex: 0 0 auto; padding: .5rem 1rem; font-size: .85rem; font-weight: 600; }
.ndx-strip-ok { background: #dcfce7; color: #166534; }
.ndx-strip-err { background: #fee2e2; color: #991b1b; }
</style>
`;

const GITIGNORE = `node_modules/
.nuxt/
.output/
.data/
`;

// Auto-imported no-op stubs for the full-cockpit "console" composables that some
// studio-integrations components (notably CredentialRevenexxSource, the "Use
// revenexx managed source" picker in the credential dialog) reach for. The
// slimmed preview has no console gateways (tenants, markets, managed SFTP / mail
// / API keys), so without these the component throws "useConsoleTenants is not
// defined" at setup and takes its sibling manual-config fields down with it —
// leaving the credential dialog with NO input fields. These stubs let that
// picker render empty instead of crashing, so manual credential creation works.
const CONSOLE_STUBS = `import { ref } from 'vue'

export function useConsoleTenants() {
  return { tenants: ref([]), onlyTenantSlug: ref(null), load: async () => {} }
}
export function useActiveMarket() {
  return {
    markets: ref([]),
    activeCode: ref(''),
    isGlobal: ref(true),
    GLOBAL_MARKET_CODE: '__global__',
    fetchMarkets: async () => {},
  }
}
export function useConsoleSftp() {
  return {
    accounts: ref([]),
    load: async () => {},
    revealPassword: async () => ({}),
    create: async () => ({}),
    refresh: async () => ({}),
  }
}
export function useMailAdmin() {
  return {
    listCredentials: async () => [],
    getCredential: async () => ({}),
    createCredential: async () => ({}),
  }
}
export function useConsoleApiKeys() {
  return { create: async () => ({ secret: '' }) }
}
`;

// Phase 1: workflow execution isn't available in the devkit preview, so the
// Workflows editor pages are off-limits until phase 2. Any navigation to them
// (deep links from the dashboard, direct URLs) bounces back to the Integrations
// dashboard. The nav entry itself is hidden via assets/css/main.css.
const HIDE_WORKFLOWS_MW = `export default defineNuxtRouteMiddleware((to) => {
  if (to.path === '/integrations/workflows' || to.path.startsWith('/integrations/workflows/')) {
    return navigateTo('/integrations')
  }
})
`;

export function previewTemplates(options: PreviewTemplateOptions): Record<string, string> {
  const env = `# Overrides the Nuxt runtimeConfig.public.* values.
NUXT_PUBLIC_INTEGRATIONS_API=${options.integrationsApiUrl}
NUXT_PUBLIC_DEV_TOKEN=dev
NUXT_PUBLIC_DEV_TENANT=dev-tenant
`;
  return {
    'package.json': PACKAGE_JSON,
    'nuxt.config.ts': NUXT_CONFIG,
    'assets/css/main.css': MAIN_CSS,
    'app.vue': APP_VUE,
    'pages/index.vue': INDEX_VUE,
    'pages/nodes.vue': NODES_VUE,
    'composables/devkit-console-stubs.ts': CONSOLE_STUBS,
    'middleware/hide-workflows.global.ts': HIDE_WORKFLOWS_MW,
    '.env': env,
    '.gitignore': GITIGNORE,
  };
}
